export const SET_CITY_WEATHER = 'SET_CITY_WEATHER';
export const CITY_WEATHER_LOADING = 'CITY_WEATHER_LODING';
export const CITY_WEATHER_LOADED = 'CITY_WEATHER_LODED';
export const CITY_WEATHER_FAILED = 'CITY_WEATHER_FAILED';