export const SET_CITY_HOURLY_WEATHER = "SET_CITY_HOURLY_WEATHER";
export const CITY_HOURLY_WEATHER_LOADING = "CITY_HOURLY_WEATHER_LOADING";
export const CITY_HOURLY_WEATHER_LOADED = "CITY_HOURLY_WEATHER_LOADED";
export const CITY_HOURLY_WEATHER_FAILED = "CITY_HOURLY_WEATHER_FAILED";